<?php

namespace Database\Seeders;

use App\Models\User\User;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        foreach (User::users()->get() as $user) {
            for ($i = 1; $i <= 3; $i++) {
                $user->products()->create([
                    'name' => [
                        'ar' => 'منتج ' . $i . ' ' . $user->name,
                        'en' => 'Product ' . $i . ' ' . $user->name,
                    ],
                    'description' => [
                        'ar' => 'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق.',
                        'en' => 'This text is an example of text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application.',
                    ],
                    'price' => $i * 100,
                ]);
            }
        }
    }
}
